#from https://github.com/cypress-io/todomvc/blob/master/.github/workflows/test-app.yml
name: Cypress tests
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main
    
jobs:
  cypress-run:
    name: Cypress run https://github.com/Its-Alann/SOEN390-Project-Team8
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Start the app
        run: npm start &

      - name: Wait for app to start
        run: |
          npx wait-on http://localhost:3000
          sleep 10

      - name: Run E2E tests with Cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          wait-on: 'http://localhost:3000'
