#from https://github.com/cypress-io/todomvc/blob/master/.github/workflows/test-app.yml
name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          component: true
          browser: chrome
          headed: true
