name: Cypress Tests

on:
  push:
    branches:
      [ main ]
  pull_request:
    branches:
      [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.1.0
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
