#from https://github.com/cypress-io/todomvc/blob/master/.github/workflows/test-app.yml
name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0
        with:
          spec: ../cypress/__tests__/AccountCreation.cy.js
