name: Cypress Tests

on:
  push:
    branches:
      [ main ]
  pull_request:
    branches:
      [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        npm ci
        npm run build --if-present
    - name: Serve production build
      run: |
        npm install -g serve
        serve -s build --no-clipboard
          
  cypress_tests:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v5.4.0
        with:
          install: false
