name: Cypress Tests

on:
  push:
    branches:
      [ main ]
  pull_request:
    branches:
      [ main ]

jobs:          
  cypress_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm ci
          npm run build --if-present
      - name: Serve production build
        run: npx serve -s build
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5.4.0
        with:
          install: false
