name: Cypress Tests

on:
  push:
    branches:
      [ main ]
  pull_request:
    branches:
      [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Start server
      run: |
        npm start &        
  cypress_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5.4.0
