name: Cypress E2E Tests

on:
  [push]
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      # now run the tests from the subfolder
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npx cypress run
