name: Merge Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest changes from main
        run: git fetch origin main

      - name: Check if branch is up-to-date with main
        run: |
          COMMITS_BEHIND=$(git rev-list --count main..HEAD)
          if [ "$COMMITS_BEHIND" -gt 0 ]; then
            echo "The branch is $COMMITS_BEHIND commit(s) behind main."
            exit 1
          fi
