name: Merge Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout main branch
        run: git checkout main

      - name: Fetch latest changes
        run: git pull

      - name: Check number of commits behind main
        id: commits-behind-main
        run: |
          COMMITS_BEHIND=$(git rev-list --count main..HEAD)
          echo "There are $COMMITS_BEHIND commits behind main"
